use Biblioteca;
#Con la base de datos “movies”, se propone crear una tabla temporal llamada “TWD” y guardar en la misma los episodios de todas las temporadas de “The Walking Dead”.
CREATE TEMPORARY TABLE TWD (temporada varchar (40),numero_episodio varchar(40),episodio varchar(300));
insert into TWD (temporada,numero_episodio,episodio) values
(1,1,"Pasado decaído ( Days Gone Bye )"),
(1,2,"Callos ( Tripas )"),
(1,3,"Solo charla con las ranas ( Díselo a las ranas )"),
(1,4,"La pandilla ( Vatos )"),
(1,5,"Wildfire ( Wildfire )"),
(1,6,"Sujeto de prueba 19 ( TS-19 )"),
(2,1,"Lo que nos espera ( lo que viene )"),
(2,2,"Sangrado ( sangría )"),
(2,3,"Todo por todo ( Salvar el último )"),
(2,4,"Cherokee Rose ( Cherokee Rose )"),
(2,5,"Chupacabras ( Chupacabras )"),
(2,6,"Secretos ( secretos )"),
(2,7,"Ya más o menos muerto ( Bastante muerto ya )"),
(2,8,"Nebraska ( Nebraska )"),
(2,9,"El dedo en el gatillo ( Triggerfinger )"),
(2,10,"Dieciocho millas, al menos ( 18 millas de distancia )"),
(2,11,"Juez, jurado y verdugo ( juez, jurado, verdugo )"),
(2,12,"Los mejores ángeles de nuestra naturaleza ( mejores ángeles )"),
(2,13,"Cerca del fuego moribundo (al lado del fuego moribundo )"),
(3,1,"Semillas ( Semilla )"),
(3,2,"Enfermo ( enfermo )"),
(3,3,"Camina conmigo ( camina conmigo )"),
(3,4,"Un asesino en el interior ( Asesino en el interior )"),
(3,5,"Dilo ( di la palabra )"),
(3,6,"La caza ( perseguida )"),
(3,7,"Cuando los muertos se acercan ( Cuando los muertos vienen llamando )"),
(3,8,"Una vida de sufrimiento ( Hecho para sufrir )"),
(3,9,"El rey del suicidio ( The Suicide King )"),
(3,10,"Con nosotros ( Inicio )"),
(3,11,"Entre dos fuegos ( no soy un Judas )"),
(3,12,"Regreso a casa ( claro )"),
(3,13,"Una flecha en la puerta ( Flecha en el poste de la puerta )"),
(3,14,"La presa ( presa )"),
(3,15,"Esta triste vida ( esta triste vida )"),
(3,16,"Bienvenido a la tumba ( Bienvenido a las tumbas )"),
(4,1,"30 días sin accidentes ( 30 días sin accidentes )"),
(4,2,"Infectado ( Infectado )"),
(4,3,"Aislamiento ( aislamiento )"),
(4,4,"Indiferencia ( indiferencia )"),
(4,5,"Internamiento ( Internamiento )"),
(4,6,"Cebo vivo ( cebo vivo )"),
(4,7,"Peso muerto ( peso muerto )"),
(4,8,"Desesperado ( demasiado lejos )"),
(4,9,"Después ( Después )"),
(4,10,"Held ( presos )"),
(4,11,"Reclamado ( reclamado )"),
(4,12,"Paréntesis ( todavía )"),
(4,13,"Solo ( solo )"),
(4,14,"El huerto ( The Grove )"),
(4,15,"Nosotros ( nosotros )"),
(4,16,"A ( A )");
#Realizar una consulta a la tabla temporal para ver los episodios de la primera temporada.
select numero_episodio,episodio from TWD 
where temporada = 1;
