-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 14:21:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_db` DEFAULT CHARACTER SET utf8 ;
USE `empresa_db` ;

-- -----------------------------------------------------
-- Table `empresa_db`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`departamento` (
  `depto_nro` VARCHAR(20) NOT NULL,
  `nombre_depto` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`depto_nro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`empleado` (
  `cod_emp` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `fecha_alta` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  `comision` VARCHAR(45) NOT NULL,
  `depto_nro` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_emp`),
  INDEX `fk_empleado_departamento_idx` (`depto_nro` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_departamento`
    FOREIGN KEY (`depto_nro`)
    REFERENCES `empresa_db`.`departamento` (`depto_nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
