-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 15:43:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empleados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empleados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empleados` DEFAULT CHARACTER SET utf8 ;
USE `empleados` ;

-- -----------------------------------------------------
-- Table `empleados`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados`.`Departamento` (
  `dpto_nro` VARCHAR(10) NOT NULL,
  `nombre_dpto` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  PRIMARY KEY (`dpto_nro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleados`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados`.`Empleado` (
  `cod_emp` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `fecha_alta` DATETIME NULL,
  `salario` INT NULL,
  `comision` INT NULL,
  `dpto_nro` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_emp`),
  INDEX `fk_Empleado_Departamento_idx` (`dpto_nro` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Departamento`
    FOREIGN KEY (`dpto_nro`)
    REFERENCES `empleados`.`Departamento` (`dpto_nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
