-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 15:48:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_db` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca_db` ;

-- -----------------------------------------------------
-- Table `biblioteca_db`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`Libro` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  `Editorial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`Autor` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Nacionalidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`LibroAutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`LibroAutor` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`LibroAutor` (
  `idAutor` INT NOT NULL,
  `idLibro` INT NOT NULL,
  INDEX `Libro_foreign_idx` (`idLibro` ASC) VISIBLE,
  INDEX `Autor_foreign_idx` (`idAutor` ASC) VISIBLE,
  CONSTRAINT `Libro_autor_foreign`
    FOREIGN KEY (`idLibro`)
    REFERENCES `biblioteca_db`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Autor_foreign`
    FOREIGN KEY (`idAutor`)
    REFERENCES `biblioteca_db`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Estudiante` (
  `idLector` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Carrera` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  PRIMARY KEY (`idLector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`Prestamo` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Prestamo` (
  `idLector` INT NOT NULL,
  `idLibro` INT NOT NULL,
  `FechaDevolucion` DATETIME NOT NULL,
  `Devuelto` BLOB NOT NULL,
  INDEX `libro_foreign_idx` (`idLibro` ASC) VISIBLE,
  INDEX `estudiante_foreign_idx` (`idLector` ASC) VISIBLE,
  CONSTRAINT `libro_foreign`
    FOREIGN KEY (`idLibro`)
    REFERENCES `biblioteca_db`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estudiante_foreign`
    FOREIGN KEY (`idLector`)
    REFERENCES `biblioteca_db`.`Estudiante` (`idLector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Inserción de datos libro
    INSERT INTO Libro (Titulo, Area, Editorial) VALUES
    ('El tránsito terreno','Filosofía','Larrosa Mas, S.L.'),
    ('Sistemas operativos','Base de Datos', 'GGG&G'),
    ('Poemas intrínsecos','Poesía', 'Deloria Editores'),
    ('El Universo: Guía de viaje','Historia', 'TechniBooks'),
    ('Las balas del bien','Novela', 'GGG&G'),
    ('La mente y el sentir','Filosofía', 'Salamandra'),
    ('Ensayos póstumos','Base de Datos', 'Deloria Editores'),
    ('La dualidad aparente','Internet', 'Larrosa Mas, S.L.'),
    ('Arquitectura y arte','Base de Datos', 'Grisham Publishing.'),
    ('Historia de Occidente','Historia', 'Salamandra'),
    ('Sentimiento popular','Poesía', 'Larrosa Mas, S.L.'),
    ('Amigos o enemigos','Novela', 'GGG&G'),
    ('La burguesía del XIX','Historia', 'Deloria Editores'),
    ('Procesadores cuánticos','Internet', 'Grisham Publishing'),
    ('Canto de esperanza','Poesía', 'McCoy Hill'),
	('Harry Potter y la piedra filosofal','Fantasía', 'Salamandra'),
    ('Harry Potter y el caliz de fuego','Fantasía', 'McCoy Hill');
    
-- Inserción de datos autores
    INSERT INTO Autor (Nombre, Nacionalidad) VALUES
    ('Dulac, George','Francesa'),
    ('Bertomeu,Andrés','Española'),
    ('Uosiken, Fred','Finlandesa'),
    ('Müller, Klaus','Italiana'),
	('Llorens, Antonias','Alemana'),
    ('Leverling, Janet','Estadounidense'),
    ('Kröpotkin,Albert','Alemana'),
    ('Bazilian, Eric','Estadounidense'),
	('Davolio, Nancy','Australiana'),
    ('Becket, Samuel','Francesa'),
    ('Dion, Paul','Britanica'),
    ('Richter, Helmut','Alemana'),
    ('Chabrier, Louis','Francesa'),
    ('Sanabria, Carmelo','Italiana'),
    ('Plasencia,Juan Luis','Española'),
    ('Santos, Miguel','Colombiana'),
    ('Montenegro, Miguel','Chilena'),
    ('J.K. Rowling.','Britanica');
    
-- Inserción de datos libro autores
	INSERT INTO LibroAutor VALUES
    (1,10),(1,13),(2,7),(15,1),(8,2),(5,3),(12,4),(6,5),
    (15,6),(2,7),(14,8),(12,9),(5,11),(14,12),(8,14),(9,15),
    (3,10),(4,13),(6,7),(8,1),(7,2),(7,3),(11,4),(12,5),
    (13,6),(3,7),(13,8),(14,9),(15,11),(17,12),(16,14),(16,15),(18,16),(18,17);
    
-- Inserción de datos libro autores
	INSERT INTO Estudiante (Nombre, Apellido, Direccion, Carrera, Edad) VALUES
    ('Juan','Perez','Calle 25#4-23','Informática',24),
    ('Filippo','Galli','Calle 45#4-89','Ciencias politicas',26),
    ('Felipe','Rodriguez','Calle 38 #5-78','Ingeniería ambiental',24),
    ('Tannia','Hernandez','Calle 38 #2-94','Ingeniería electrónica',22),
    ('Lucía','Rojas','Calle 78 #4-34','Informática',18),
    ('Maria','Gonzalez','Calle 23 # 4-56','Administración de empresas',21);
    
-- Inserción de datos libro autores
	INSERT INTO Prestamo VALUES
    (1,10,'2021-05-12',false),(2,13,'2021-08-25',true),(3,7,'2021-07-16',false),(4,1,'2021-03-23',false),
    (4,2,'2021-07-16',true),(6,3,'2021-04-25',false),(1,4,'2021-09-20',true),(2,5,'2021-10-01',true),
    (3,5,'2021-03-18',false),(4,18,'2021-01-18',false),(5,10,'2021-07-14',false),(6,7,'2021-08-22',false),
    (1,8,'2021-07-16',false),(2,7,'2021-11-09',false),(3,13,'2021-12-06',false),(4,14,'2021-06-17',false),
    (5,6,'2021-06-21',false),(6,9,'2021-07-16',false),(1,6,'2021-04-29',false),(2,17,'2021-05-30',false),
    (3,17,'2021-05-04',false),(4,11,'2021-08-11',false),(5,12,'2021-05-03',false),(6,13,'2021-07-16',false);
    