-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 17:12:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
​
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
​
-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------
​
-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_db` DEFAULT CHARACTER SET utf8 ;
USE `empresa_db` ;
​
-- -----------------------------------------------------
-- Table `empresa_db`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`DEPARTAMENTO` (
  `ref_dpto` CHAR(6) NOT NULL DEFAULT 'D-000-',
  `depto_nro` VARCHAR(45) NOT NULL,
  `nombre_depto` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  PRIMARY KEY (`ref_dpto`, `depto_nro`))
ENGINE = InnoDB;
​
​
-- -----------------------------------------------------
-- Table `empresa_db`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`EMPLEADO` (
  `ref` CHAR(2) NOT NULL DEFAULT 'E-',
  `cod_emp` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `fecha_alta` DATE NULL,
  `salario` DOUBLE NULL,
  `comision` DOUBLE NULL,
  `ref_dpto` CHAR(5) NOT NULL,
  `depto_nro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ref`, `cod_emp`, `ref_dpto`, `depto_nro`),
  INDEX `fk_EMPLEADO_DEPARTAMENTO_idx` (`ref_dpto` ASC, `depto_nro` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_DEPARTAMENTO`
    FOREIGN KEY (`ref_dpto` , `depto_nro`)
    REFERENCES `empresa_db`.`DEPARTAMENTO` (`ref_dpto` , `depto_nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
​
​
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;