-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 12:15:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet`.`Planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`Planes` (
  `idPlan` INT NOT NULL,
  `velocidad` INT NOT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  `descuento` DECIMAL(2,2) NULL,
  PRIMARY KEY (`idPlan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`Clientes` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `Planes_idPlan` INT NOT NULL,
  PRIMARY KEY (`dni`, `Planes_idPlan`),
  INDEX `fk_Clientes_Planes_idx` (`Planes_idPlan` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Planes`
    FOREIGN KEY (`Planes_idPlan`)
    REFERENCES `empresa_internet`.`Planes` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
