-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 16:07:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empleado_departamento` DEFAULT CHARACTER SET utf8 ;
USE `empleado_departamento` ;

-- -----------------------------------------------------
-- Table `mydb`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleado_departamento`.`DEPARTAMENTO` (
  `depto_nro` VARCHAR(10) NOT NULL,
  `nombre_depto` VARCHAR(20) NOT NULL,
  `localidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`depto_nro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleado_departamento`.`EMPLEADO` (
  `cod_emp` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `salario` INT NOT NULL,
  `comision` INT NOT NULL,
  `depto_nro` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_emp`, `depto_nro`),
  INDEX `fk_EMPLEADO_DEPARTAMENTO_idx` (`depto_nro` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_DEPARTAMENTO`
    FOREIGN KEY (`depto_nro`)
    REFERENCES `empleado_departamento`.`DEPARTAMENTO` (`depto_nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- ------------------------------------------------------------------------

INSERT INTO DEPARTAMENTO VALUES("D-000-1", "Software", "Los Tigres");
INSERT INTO DEPARTAMENTO VALUES("D-000-2", "Sistemas", "Guadalupe");
INSERT INTO DEPARTAMENTO VALUES("D-000-3", "Contabilidad", "La Roca");
INSERT INTO DEPARTAMENTO VALUES("D-000-4", "Ventas", "Plata");

INSERT INTO EMPLEADO VALUES("E-0001", "César", "Piñero", "Vendedor", '2018-05-12', 80000, 15000, "D-000-4");
INSERT INTO EMPLEADO VALUES("E-0002", "Yosep", "Kowaleski", "Analista", '2015-07-14', 140000, 0, "D-000-2");
INSERT INTO EMPLEADO VALUES("E-0003", "Mariela", "Barrios", "Director", '2014-06-05', 185000, 0, "D-000-3");
INSERT INTO EMPLEADO VALUES("E-0004", "Jonathan", "Aguilera", "Vendedor", '2015-06-03', 85000, 10000, "D-000-4");
INSERT INTO EMPLEADO VALUES("E-0005", "Daniel", "Brezezicki", "Vendedor", '2018-03-03', 83000, 10000, "D-000-4");
INSERT INTO EMPLEADO VALUES("E-0006", "Mito", "Barchuk", "Presidente", '2014-06-05', 190000, 0, "D-000-3");
INSERT INTO EMPLEADO VALUES("E-0007", "Emilio", "Galarza", "Desarrollador", '2014-08-02', 60000, 0, "D-000-1");

-- ------------------------------------------------------------------------

SELECT e.nombre, e.puesto, d.localidad FROM EMPLEADO e
INNER JOIN DEPARTAMENTO d ON e.depto_nro = d.depto_nro WHERE e.puesto = "Vendedor";

select d.depto_nro, d.nombre_depto, d.localidad, count(*) as cantidad_de_empleados
from DEPARTAMENTO d inner join empleado e on d.depto_nro = e.depto_nro
group by d.depto_nro, d.nombre_depto having cantidad_de_empleados>=3;

select nombre, salario, nombre_depto from EMPLEADO
inner join DEPARTAMENTO on EMPLEADO.depto_nro = DEPARTAMENTO.depto_nro
where EMPLEADO.puesto = (select puesto from EMPLEADO where(nombre="Mito" and apellido="Barchuk"));

select * from empleado
where depto_nro = "D-000-3" order by nombre;

select nombre from empleado order by salario limit 1;

select * from empleado inner join
departamento dpto on empleado.depto_nro = dpto.depto_nro
where dpto.nombre_depto = "Ventas"
and salario = (select max(salario) from empleado where dpto.depto_nro = empleado.depto_nro );
