-- MySQL Script generated by MySQL Workbench
-- Thu Aug 25 16:00:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`provincia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudad_provincia_idx` (`provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `empresa_internet`.`provincia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`domicilio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `ciudad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_domicilio_ciudad1_idx` (`ciudad_id` ASC) VISIBLE,
  CONSTRAINT `fk_domicilio_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `empresa_internet`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `birth_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `mb` VARCHAR(45) NOT NULL,
  `value` INT NOT NULL,
  `discount_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plan_discount1_idx` (`discount_id` ASC) VISIBLE,
  CONSTRAINT `fk_plan_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `empresa_internet`.`discount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`domicilio_has_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`domicilio_has_cliente` (
  `domicilio_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`domicilio_id`, `cliente_id`),
  INDEX `fk_domicilio_has_cliente_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_domicilio_has_cliente_domicilio1_idx` (`domicilio_id` ASC) VISIBLE,
  CONSTRAINT `fk_domicilio_has_cliente_domicilio1`
    FOREIGN KEY (`domicilio_id`)
    REFERENCES `empresa_internet`.`domicilio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_has_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `empresa_internet`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`domicilio_has_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`domicilio_has_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plan_id` INT NOT NULL,
  `domicilio_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  INDEX `fk_domicilio_has_plan_plan1_idx` (`plan_id` ASC) VISIBLE,
  INDEX `fk_domicilio_has_plan_domicilio1_idx` (`domicilio_id` ASC) VISIBLE,
  INDEX `fk_domicilio_has_plan_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_domicilio_has_plan_plan1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `empresa_internet`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_has_plan_domicilio1`
    FOREIGN KEY (`domicilio_id`)
    REFERENCES `empresa_internet`.`domicilio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_has_plan_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `empresa_internet`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
