-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 15:45:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_vivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_vivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_vivo` DEFAULT CHARACTER SET utf8 ;
USE `empresa_vivo` ;

-- -----------------------------------------------------
-- Table `empresa_vivo`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_vivo`.`departamentos` (
  `depto_nro` VARCHAR(7) NOT NULL,
  `nombre_depto` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`depto_nro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_vivo`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_vivo`.`empleados` (
  `cod_emp` VARCHAR(6) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `fecha_alta` DATETIME NOT NULL,
  `salario` INT NOT NULL,
  `comision` INT NOT NULL,
  `empleadoscol` VARCHAR(45) NULL,
  `depto_nro` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`cod_emp`, `depto_nro`),
  INDEX `fk_empleados_departamentos_idx` (`depto_nro` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_departamentos`
    FOREIGN KEY (`depto_nro`)
    REFERENCES `empresa_vivo`.`departamentos` (`depto_nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO departamentos VALUE ("D-0001", "Software", "Los Tigres");
INSERT INTO departamentos VALUE ("D-0002", "Sistemas", "Guadalupe");
INSERT INTO departamentos VALUE ("D-0003", "Contabilidad", "La Roca");
INSERT INTO departamentos VALUE ("D-0004", "Ventas", "Plata");

INSERT INTO empleados VALUE ("E-0001", "César", "Piñero", "Vendedor", '2018-05-12', 80000, 15000, "D-0004");
INSERT INTO empleados VALUE ("E-0002", "Yosep", "Kowaleski", "Analista", '2015-07-14', 140000, 0, "D-0002");
INSERT INTO empleados VALUE ("E-0003", "Mariela", "Barrios", "Director", '2014-06-05', 185000, 0, "D-0003");
INSERT INTO empleados VALUE ("E-0004", "Jonathan", "Aguilera", "Vendedor", '2015-06-03', 85000, 10000, "D-0004");
INSERT INTO empleados VALUE ("E-0005", "Daniel", "Brezezicki", "Vendedor", '2018-03-03', 83000, 10000, "D-0004");
INSERT INTO empleados VALUE ("E-0006", "Mito", "Barchuk", "Presidente", '2014-06-05', 190000, 0, "D-0003");
INSERT INTO empleados VALUE ("E-0007", "Emilio", "Galarza", "Desarrollador", '2014-08-02', 60000, 0, "D-0001");