-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 16:19:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresaSqlAdv` DEFAULT CHARACTER SET utf8 ;
USE `empresaSqlAdv` ;

-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresaSqlAdv`.`department` ;

CREATE TABLE IF NOT EXISTS `empresaSqlAdv`.`department` (
  `departmentNumber` VARCHAR(10) NOT NULL,
  `departmentName` VARCHAR(45) NOT NULL,
  `departmentCity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`departmentNumber`),
  UNIQUE INDEX `idEmployees_UNIQUE` (`departmentNumber` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresaSqlAdv`.`employees` ;

CREATE TABLE IF NOT EXISTS `empresaSqlAdv`.`employees` (
  `employeesCode` VARCHAR(20) NOT NULL,
  `employeesName` VARCHAR(45) NOT NULL,
  `employeesLastname` VARCHAR(45) NOT NULL,
  `employeesPosition` VARCHAR(45) NOT NULL,
  `employeesStartdate` DATE NOT NULL,
  `employeesSalary` INT NOT NULL,
  `employeesComission` INT NOT NULL DEFAULT 0,
  `departmentNumber` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`employeesCode`),
  UNIQUE INDEX `idEmployees_UNIQUE` (`employeesCode` ASC) VISIBLE,
  INDEX `fk_employees_department_idx` (`departmentNumber` ASC) VISIBLE,
  CONSTRAINT `fk_employees_department`
    FOREIGN KEY (`departmentNumber`)
    REFERENCES `mydb`.`department` (`departmentNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
