-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 16:54:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_db` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca_db` ;

-- -----------------------------------------------------
-- Table `biblioteca_db`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Autor` (
  `idAutor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Prestamo` (
  `idLector` INT NOT NULL,
  `lidLibro` INT NOT NULL,
  `fechaPrestamo` DATE NULL,
  `fechaDevolucion` DATE NULL,
  `devuelto` TINYINT NULL,
  PRIMARY KEY (`idLector`, `lidLibro`),
  INDEX `fk_Estudiante_has_Libro_Libro1_idx` (`lidLibro` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Libro_Estudiante1_idx` (`idLector` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Libro_Estudiante1`
    FOREIGN KEY (`idLector`)
    REFERENCES `biblioteca_db`.`Estudiante` (`idLector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Libro_Libro1`
    FOREIGN KEY (`lidLibro`)
    REFERENCES `biblioteca_db`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Libro` (
  `idLibro` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `editorial` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Estudiante` (
  `idLector` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `carrera` VARCHAR(45) NULL,
  `edad` INT NULL,
  PRIMARY KEY (`idLector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Libro_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Libro_has_Autor` (
  `Libro_idLibro` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`Libro_idLibro`, `Autor_idAutor`),
  INDEX `fk_Libro_has_Autor_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Libro_has_Autor_Libro_idx` (`Libro_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_has_Autor_Libro`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `biblioteca_db`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `biblioteca_db`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`LibroAutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`LibroAutor` (
  `idAutor` INT NOT NULL,
  `idLibro` INT NOT NULL,
  PRIMARY KEY (`idAutor`, `idLibro`),
  INDEX `fk_Autor_has_Libro_Libro1_idx` (`idLibro` ASC) VISIBLE,
  INDEX `fk_Autor_has_Libro_Autor1_idx` (`idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Libro_Autor1`
    FOREIGN KEY (`idAutor`)
    REFERENCES `biblioteca_db`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Libro_Libro1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `biblioteca_db`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`Prestamo` (
  `idLector` INT NOT NULL,
  `lidLibro` INT NOT NULL,
  `fechaPrestamo` DATE NULL,
  `fechaDevolucion` DATE NULL,
  `devuelto` TINYINT NULL,
  PRIMARY KEY (`idLector`, `lidLibro`),
  INDEX `fk_Estudiante_has_Libro_Libro1_idx` (`lidLibro` ASC) VISIBLE,
  INDEX `fk_Estudiante_has_Libro_Estudiante1_idx` (`idLector` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_has_Libro_Estudiante1`
    FOREIGN KEY (`idLector`)
    REFERENCES `biblioteca_db`.`Estudiante` (`idLector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Libro_Libro1`
    FOREIGN KEY (`lidLibro`)
    REFERENCES `biblioteca_db`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
