-- MySQL Script generated by MySQL Workbench
-- Fri Aug 26 14:56:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema facturas_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `facturas_db` ;

-- -----------------------------------------------------
-- Schema facturas_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturas_db` DEFAULT CHARACTER SET utf8 ;
USE `facturas_db` ;

-- -----------------------------------------------------
-- Table `facturas_db`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturas_db`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `facturas_db`.`Cliente` (
  `id_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(40) NULL,
  `apellido_cliente` VARCHAR(40) NULL,
  `direccion_cliente` VARCHAR(40) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturas_db`.`Articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturas_db`.`Articulo` ;

CREATE TABLE IF NOT EXISTS `facturas_db`.`Articulo` (
  `id_articulo` INT NOT NULL,
  `descripcion_articulo` VARCHAR(45) NULL,
  `iva` DECIMAL(10,0) NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturas_db`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturas_db`.`Factura` ;

CREATE TABLE IF NOT EXISTS `facturas_db`.`Factura` (
  `id_factura` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `fecha_factura` DATETIME NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_Factura_Cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `facturas_db`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturas_db`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturas_db`.`Pago` ;

CREATE TABLE IF NOT EXISTS `facturas_db`.`Pago` (
  `id_pago` VARCHAR(45) NOT NULL,
  `id_factura` INT NOT NULL,
  `forma_pago` DECIMAL(10,0) NULL,
  `cantidad` DECIMAL(10,0) NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_Pago_Factura1_idx` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_Factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `facturas_db`.`Factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturas_db`.`FacturaArticulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturas_db`.`FacturaArticulo` ;

CREATE TABLE IF NOT EXISTS `facturas_db`.`FacturaArticulo` (
  `id_factura` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT(11) NULL,
  PRIMARY KEY (`id_factura`, `id_articulo`),
  INDEX `fk_Factura_has_Articulo_Articulo1_idx` (`id_articulo` ASC) VISIBLE,
  INDEX `fk_Factura_has_Articulo_Factura_idx` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_has_Articulo_Factura`
    FOREIGN KEY (`id_factura`)
    REFERENCES `facturas_db`.`Factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Articulo_Articulo1`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `facturas_db`.`Articulo` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
